apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: languagebattle-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  languagebattle-web
  labels:
    name:  languagebattle-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  languagebattle-web
    spec:
      containers:
      - image: chzbrgr71/languagebattle-web:v1
        name:  languagebattle-web-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        env:
        - name:  API
          value:  http://api:3000/
        ports:
        - containerPort:  8080
          name:  lang-web
        imagePullPolicy: Always
      restartPolicy: Always